# Generated by Django 4.2.7 on 2025-12-04 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('general', 'General'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('note', 'Note')], default='general', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('flexible_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patient')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'record_type'], name='medical_rec_patient_f0d433_idx'), models.Index(fields=['created_at'], name='medical_rec_created_d796b8_idx')],
            },
        ),
    ]
