# Generated by Django 4.2.7 on 2025-12-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('ssn_legacy', models.CharField(blank=True, db_column='ssn', max_length=20)),
                ('ssn_number', models.CharField(blank=True, max_length=20)),
                ('ssn_verified', models.BooleanField(default=False)),
                ('ssn_verification_date', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='patients_email_bf0efb_idx'), models.Index(fields=['ssn_legacy'], name='patients_ssn_4dd3eb_idx'), models.Index(fields=['ssn_number'], name='patients_ssn_num_b23919_idx')],
            },
        ),
    ]
